# Generated by Django 2.1.4 on 2019-07-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_open', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ticker_close', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ticker_volume', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ticker_low', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ticker_high', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ticker_bulk_volume', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ticker_time', models.CharField(max_length=40)),
                ('ticker_updated_time', models.DateTimeField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pair')),
            ],
        ),
    ]
