# Generated by Django 2.1.4 on 2019-07-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exchange_pair_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pair', unique_for_date='ticker_updated_time'),
        ),
    ]
