# Generated by Django 2.1.4 on 2019-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190727_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
