# Generated by Django 2.1.4 on 2019-08-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pair_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pair'),
        ),
    ]
